web:
  image: steynovich/spotweb:latest
  links:
  - database:mysql
  ports:
  - "80:80"
  volumes:
  - spotweb_cache:/var/www/html/spotweb/cache
database:
  environment:
    MYSQL_ROOT_PASSWORD: randompw
    MYSQL_USER: spotweb
    MYSQL_PASSWORD: spotweb
    MYSQL_DATABASE: spotweb
  image: mariadb:latest
  volumes:
  - spotweb_db:/var/lib/mysql
