version: '2'
services:
  database:
    image: mariadb:10.2.8
    environment:
      MYSQL_DATABASE: OBFUSCATED
      MYSQL_PASSWORD: spotweb
      MYSQL_ROOT_PASSWORD: OBFUSCATED
      MYSQL_USER: spotweb
    volumes:
    - /mnt/vol/spotweb_db:/var/lib/mysql
  web:
    image: steynovich/spotweb:20170826
    volumes:
    - /mnt/vol/spotweb_cache:/var/www/html/spotweb/cache
    links:
    - database:mysql
